// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package user_detail

import (
	"database/sql"
)

type UserDetail struct {
	ID        int32
	UserGuid  string
	FirstName sql.NullString
	LastName  sql.NullString
	Phone     sql.NullString
	Avatar    sql.NullString
	Address   sql.NullString
	Createdat int64
	Updatedat sql.NullInt64
	Deletedat sql.NullInt64
}
