// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { StatusMessage } from "../../statusmsg/v1/statusmsg_pb";
import { file_statusmsg_v1_statusmsg } from "../../statusmsg/v1/statusmsg_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v1/auth.proto.
 */
export const file_auth_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL2F1dGgucHJvdG8SB2F1dGgudjEiLwoMTG9naW5SZXF1ZXN0Eg0KBWVtYWlsGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJImkKDUxvZ2luUmVzcG9uc2USFAoMYWNjZXNzX3Rva2VuGAEgASgJEhUKDXJlZnJlc2hfdG9rZW4YAiABKAkSKwoGc3RhdHVzGAMgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2UiQwoNU2lnblVwUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCRIRCglmdWxsX25hbWUYAyABKAkiPQoOU2lnblVwUmVzcG9uc2USKwoGc3RhdHVzGAEgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2UiMQoTVmVyaWZ5U2lnblVwUmVxdWVzdBINCgVlbWFpbBgBIAEoCRILCgNvdHAYAiABKAkiQwoUVmVyaWZ5U2lnblVwUmVzcG9uc2USKwoGc3RhdHVzGAEgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2UiLAoTUmVmcmVzaFRva2VuUmVxdWVzdBIVCg1yZWZyZXNoX3Rva2VuGAEgASgJInAKFFJlZnJlc2hUb2tlblJlc3BvbnNlEhQKDGFjY2Vzc190b2tlbhgBIAEoCRIVCg1yZWZyZXNoX3Rva2VuGAIgASgJEisKBnN0YXR1cxgDIAEoCzIbLnN0YXR1c21zZy52MS5TdGF0dXNNZXNzYWdlIg8KDUxvZ291dFJlcXVlc3QiPQoOTG9nb3V0UmVzcG9uc2USKwoGc3RhdHVzGAEgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2VCNVozZ2l0aHViLmNvbS9uZ29jaHV5azgxMi9wcm90by1iZHMvZ2VuL2F1dGgvdjE7YXV0aHYxYgZwcm90bzM", [file_statusmsg_v1_statusmsg]);

/**
 * @generated from message auth.v1.LoginRequest
 */
export type LoginRequest = Message<"auth.v1.LoginRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message auth.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 0);

/**
 * @generated from message auth.v1.LoginResponse
 */
export type LoginResponse = Message<"auth.v1.LoginResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 3;
   */
  status?: StatusMessage;
};

/**
 * Describes the message auth.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 1);

/**
 * -----
 *
 * @generated from message auth.v1.SignUpRequest
 */
export type SignUpRequest = Message<"auth.v1.SignUpRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * @generated from field: string full_name = 3;
   */
  fullName: string;
};

/**
 * Describes the message auth.v1.SignUpRequest.
 * Use `create(SignUpRequestSchema)` to create a new message.
 */
export const SignUpRequestSchema: GenMessage<SignUpRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 2);

/**
 * @generated from message auth.v1.SignUpResponse
 */
export type SignUpResponse = Message<"auth.v1.SignUpResponse"> & {
  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 1;
   */
  status?: StatusMessage;
};

/**
 * Describes the message auth.v1.SignUpResponse.
 * Use `create(SignUpResponseSchema)` to create a new message.
 */
export const SignUpResponseSchema: GenMessage<SignUpResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 3);

/**
 * @generated from message auth.v1.VerifySignUpRequest
 */
export type VerifySignUpRequest = Message<"auth.v1.VerifySignUpRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string otp = 2;
   */
  otp: string;
};

/**
 * Describes the message auth.v1.VerifySignUpRequest.
 * Use `create(VerifySignUpRequestSchema)` to create a new message.
 */
export const VerifySignUpRequestSchema: GenMessage<VerifySignUpRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 4);

/**
 * @generated from message auth.v1.VerifySignUpResponse
 */
export type VerifySignUpResponse = Message<"auth.v1.VerifySignUpResponse"> & {
  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 1;
   */
  status?: StatusMessage;
};

/**
 * Describes the message auth.v1.VerifySignUpResponse.
 * Use `create(VerifySignUpResponseSchema)` to create a new message.
 */
export const VerifySignUpResponseSchema: GenMessage<VerifySignUpResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 5);

/**
 * @generated from message auth.v1.RefreshTokenRequest
 */
export type RefreshTokenRequest = Message<"auth.v1.RefreshTokenRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.v1.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 6);

/**
 * @generated from message auth.v1.RefreshTokenResponse
 */
export type RefreshTokenResponse = Message<"auth.v1.RefreshTokenResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 3;
   */
  status?: StatusMessage;
};

/**
 * Describes the message auth.v1.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export const RefreshTokenResponseSchema: GenMessage<RefreshTokenResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 7);

/**
 * @generated from message auth.v1.LogoutRequest
 */
export type LogoutRequest = Message<"auth.v1.LogoutRequest"> & {
};

/**
 * Describes the message auth.v1.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 8);

/**
 * @generated from message auth.v1.LogoutResponse
 */
export type LogoutResponse = Message<"auth.v1.LogoutResponse"> & {
  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 1;
   */
  status?: StatusMessage;
};

/**
 * Describes the message auth.v1.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 9);

