// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file statusmsg/v1/statusmsg.proto (package statusmsg.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file statusmsg/v1/statusmsg.proto.
 */
export const file_statusmsg_v1_statusmsg: GenFile = /*@__PURE__*/
  fileDesc("ChxzdGF0dXNtc2cvdjEvc3RhdHVzbXNnLnByb3RvEgxzdGF0dXNtc2cudjEiRwoNU3RhdHVzTWVzc2FnZRImCgRjb2RlGAEgASgOMhguc3RhdHVzbXNnLnYxLlN0YXR1c0NvZGUSDgoGZXh0cmFzGAIgAygJKscBCgpTdGF0dXNDb2RlEhsKF1NUQVRVU19DT0RFX1VOU1BFQ0lGSUVEEAASFwoTU1RBVFVTX0NPREVfU1VDQ0VTUxABEiEKHVNUQVRVU19DT0RFX1ZBTElEQVRJT05fRkFJTEVEEAISIQodU1RBVFVTX0NPREVfVE9PX01BTllfUkVRVUVTVFMQAxIeChpTVEFUVVNfQ09ERV9JTlRFUk5BTF9FUlJPUhAEEh0KGVNUQVRVU19DT0RFX1VOS05PV05fRVJST1IQBUI9WjtnaXRodWIuY29tL25nb2NodXlrODEyL3Byb3RvLWJkcy9nZW4vc3RhdHVzbXNnL3YxO3N0YXR1c21zZ2IGcHJvdG8z");

/**
 * @generated from message statusmsg.v1.StatusMessage
 */
export type StatusMessage = Message<"statusmsg.v1.StatusMessage"> & {
  /**
   * @generated from field: statusmsg.v1.StatusCode code = 1;
   */
  code: StatusCode;

  /**
   * @generated from field: repeated string extras = 2;
   */
  extras: string[];
};

/**
 * Describes the message statusmsg.v1.StatusMessage.
 * Use `create(StatusMessageSchema)` to create a new message.
 */
export const StatusMessageSchema: GenMessage<StatusMessage> = /*@__PURE__*/
  messageDesc(file_statusmsg_v1_statusmsg, 0);

/**
 * @generated from enum statusmsg.v1.StatusCode
 */
export enum StatusCode {
  /**
   * @generated from enum value: STATUS_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_CODE_SUCCESS = 1;
   */
  SUCCESS = 1,

  /**
   * @generated from enum value: STATUS_CODE_VALIDATION_FAILED = 2;
   */
  VALIDATION_FAILED = 2,

  /**
   * @generated from enum value: STATUS_CODE_TOO_MANY_REQUESTS = 3;
   */
  TOO_MANY_REQUESTS = 3,

  /**
   * @generated from enum value: STATUS_CODE_INTERNAL_ERROR = 4;
   */
  INTERNAL_ERROR = 4,

  /**
   * @generated from enum value: STATUS_CODE_UNKNOWN_ERROR = 5;
   */
  UNKNOWN_ERROR = 5,
}

/**
 * Describes the enum statusmsg.v1.StatusCode.
 */
export const StatusCodeSchema: GenEnum<StatusCode> = /*@__PURE__*/
  enumDesc(file_statusmsg_v1_statusmsg, 0);

