// @generated by protoc-gen-es v2.2.0 with parameter "target=js"
// @generated from file property/v1/amenity.proto (package property.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_utils_v1_utils } from "../../utils/v1/utils_pb";
import { file_statusmsg_v1_statusmsg } from "../../statusmsg/v1/statusmsg_pb";

/**
 * Describes the file property/v1/amenity.proto.
 */
export const file_property_v1_amenity = /*@__PURE__*/
  fileDesc("Chlwcm9wZXJ0eS92MS9hbWVuaXR5LnByb3RvEgtwcm9wZXJ0eS52MSJNCgxBbWVuaXR5TW9kZWwSDAoEZ3VpZBgCIAEoCRIMCgRuYW1lGAMgASgJEhMKC2Rlc2NyaXB0aW9uGAQgASgJEgwKBGljb24YBSABKAkiVgoVRmV0Y2hBbWVuaXRpZXNSZXF1ZXN0EgwKBG5hbWUYASABKAkSLwoKcGFnaW5hdGlvbhgDIAEoCzIbLnV0aWxzLnYxLlBhZ2luYXRpb25SZXF1ZXN0IqEBChZGZXRjaEFtZW5pdGllc1Jlc3BvbnNlEigKBWl0ZW1zGAEgAygLMhkucHJvcGVydHkudjEuQW1lbml0eU1vZGVsEjAKCnBhZ2luYXRpb24YAiABKAsyHC51dGlscy52MS5QYWdpbmF0aW9uUmVzcG9uc2USKwoGc3RhdHVzGAMgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2UihQEKHlNlYXJjaEFkdmFuY2VBbWVuaXRpZXNSZXNwb25zZRInCgRyb3dzGAEgAygLMhkucHJvcGVydHkudjEuQW1lbml0eU1vZGVsEg0KBXRvdGFsGAIgASgDEisKBnN0YXR1cxgDIAEoCzIbLnN0YXR1c21zZy52MS5TdGF0dXNNZXNzYWdlIkcKFENyZWF0ZUFtZW5pdHlSZXF1ZXN0EgwKBG5hbWUYASABKAkSEwoLZGVzY3JpcHRpb24YAiABKAkSDAoEaWNvbhgDIAEoCSJEChVDcmVhdGVBbWVuaXR5UmVzcG9uc2USKwoGc3RhdHVzGAEgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2UiVQoUVXBkYXRlQW1lbml0eVJlcXVlc3QSDAoEbmFtZRgBIAEoCRITCgtkZXNjcmlwdGlvbhgCIAEoCRIMCgRpY29uGAMgASgJEgwKBGd1aWQYBCABKAkiRAoVVXBkYXRlQW1lbml0eVJlc3BvbnNlEisKBnN0YXR1cxgBIAEoCzIbLnN0YXR1c21zZy52MS5TdGF0dXNNZXNzYWdlIiQKFERlbGV0ZUFtZW5pdHlSZXF1ZXN0EgwKBGd1aWQYASABKAkiRAoVRGVsZXRlQW1lbml0eVJlc3BvbnNlEisKBnN0YXR1cxgBIAEoCzIbLnN0YXR1c21zZy52MS5TdGF0dXNNZXNzYWdlQj1aO2dpdGh1Yi5jb20vbmdvY2h1eWs4MTIvcHJvdG8tYmRzL2dlbi9wcm9wZXJ0eS92MTtwcm9wZXJ0eXYxYgZwcm90bzM", [file_utils_v1_utils, file_statusmsg_v1_statusmsg]);

/**
 * Describes the message property.v1.AmenityModel.
 * Use `create(AmenityModelSchema)` to create a new message.
 */
export const AmenityModelSchema = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 0);

/**
 * Describes the message property.v1.FetchAmenitiesRequest.
 * Use `create(FetchAmenitiesRequestSchema)` to create a new message.
 */
export const FetchAmenitiesRequestSchema = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 1);

/**
 * Describes the message property.v1.FetchAmenitiesResponse.
 * Use `create(FetchAmenitiesResponseSchema)` to create a new message.
 */
export const FetchAmenitiesResponseSchema = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 2);

/**
 * Describes the message property.v1.SearchAdvanceAmenitiesResponse.
 * Use `create(SearchAdvanceAmenitiesResponseSchema)` to create a new message.
 */
export const SearchAdvanceAmenitiesResponseSchema = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 3);

/**
 * Describes the message property.v1.CreateAmenityRequest.
 * Use `create(CreateAmenityRequestSchema)` to create a new message.
 */
export const CreateAmenityRequestSchema = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 4);

/**
 * Describes the message property.v1.CreateAmenityResponse.
 * Use `create(CreateAmenityResponseSchema)` to create a new message.
 */
export const CreateAmenityResponseSchema = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 5);

/**
 * Describes the message property.v1.UpdateAmenityRequest.
 * Use `create(UpdateAmenityRequestSchema)` to create a new message.
 */
export const UpdateAmenityRequestSchema = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 6);

/**
 * Describes the message property.v1.UpdateAmenityResponse.
 * Use `create(UpdateAmenityResponseSchema)` to create a new message.
 */
export const UpdateAmenityResponseSchema = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 7);

/**
 * Describes the message property.v1.DeleteAmenityRequest.
 * Use `create(DeleteAmenityRequestSchema)` to create a new message.
 */
export const DeleteAmenityRequestSchema = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 8);

/**
 * Describes the message property.v1.DeleteAmenityResponse.
 * Use `create(DeleteAmenityResponseSchema)` to create a new message.
 */
export const DeleteAmenityResponseSchema = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 9);

