// @generated by protoc-gen-es v2.2.0 with parameter "target=js"
// @generated from file property/v1/property_service.proto (package property.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_property_v1_amenity } from "./amenity_pb";
import { file_utils_v1_utils } from "../../utils/v1/utils_pb";

/**
 * Describes the file property/v1/property_service.proto.
 */
export const file_property_v1_property_service = /*@__PURE__*/
  fileDesc("CiJwcm9wZXJ0eS92MS9wcm9wZXJ0eV9zZXJ2aWNlLnByb3RvEgtwcm9wZXJ0eS52MTLlAwoPUHJvcGVydHlTZXJ2aWNlElsKDkZldGNoQW1lbml0aWVzEiIucHJvcGVydHkudjEuRmV0Y2hBbWVuaXRpZXNSZXF1ZXN0GiMucHJvcGVydHkudjEuRmV0Y2hBbWVuaXRpZXNSZXNwb25zZSIAEmcKFlNlYXJjaEFkdmFuY2VBbWVuaXRpZXMSHi51dGlscy52MS5TZWFyY2hBZHZhbmNlUmVxdWVzdBorLnByb3BlcnR5LnYxLlNlYXJjaEFkdmFuY2VBbWVuaXRpZXNSZXNwb25zZSIAElgKDUNyZWF0ZUFtZW5pdHkSIS5wcm9wZXJ0eS52MS5DcmVhdGVBbWVuaXR5UmVxdWVzdBoiLnByb3BlcnR5LnYxLkNyZWF0ZUFtZW5pdHlSZXNwb25zZSIAElgKDVVwZGF0ZUFtZW5pdHkSIS5wcm9wZXJ0eS52MS5VcGRhdGVBbWVuaXR5UmVxdWVzdBoiLnByb3BlcnR5LnYxLlVwZGF0ZUFtZW5pdHlSZXNwb25zZSIAElgKDURlbGV0ZUFtZW5pdHkSIS5wcm9wZXJ0eS52MS5EZWxldGVBbWVuaXR5UmVxdWVzdBoiLnByb3BlcnR5LnYxLkRlbGV0ZUFtZW5pdHlSZXNwb25zZSIAQj1aO2dpdGh1Yi5jb20vbmdvY2h1eWs4MTIvcHJvdG8tYmRzL2dlbi9wcm9wZXJ0eS92MTtwcm9wZXJ0eXYxYgZwcm90bzM", [file_property_v1_amenity, file_utils_v1_utils]);

/**
 * @generated from service property.v1.PropertyService
 */
export const PropertyService = /*@__PURE__*/
  serviceDesc(file_property_v1_property_service, 0);

