// @generated by protoc-gen-es v2.2.0 with parameter "target=js"
// @generated from file statusmsg/v1/statusmsg.proto (package statusmsg.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file statusmsg/v1/statusmsg.proto.
 */
export const file_statusmsg_v1_statusmsg = /*@__PURE__*/
  fileDesc("ChxzdGF0dXNtc2cvdjEvc3RhdHVzbXNnLnByb3RvEgxzdGF0dXNtc2cudjEiRwoNU3RhdHVzTWVzc2FnZRImCgRjb2RlGAEgASgOMhguc3RhdHVzbXNnLnYxLlN0YXR1c0NvZGUSDgoGZXh0cmFzGAIgAygJKscBCgpTdGF0dXNDb2RlEhsKF1NUQVRVU19DT0RFX1VOU1BFQ0lGSUVEEAASFwoTU1RBVFVTX0NPREVfU1VDQ0VTUxABEiEKHVNUQVRVU19DT0RFX1ZBTElEQVRJT05fRkFJTEVEEAISIQodU1RBVFVTX0NPREVfVE9PX01BTllfUkVRVUVTVFMQAxIeChpTVEFUVVNfQ09ERV9JTlRFUk5BTF9FUlJPUhAEEh0KGVNUQVRVU19DT0RFX1VOS05PV05fRVJST1IQBUI9WjtnaXRodWIuY29tL25nb2NodXlrODEyL3Byb3RvLWJkcy9nZW4vc3RhdHVzbXNnL3YxO3N0YXR1c21zZ2IGcHJvdG8z");

/**
 * Describes the message statusmsg.v1.StatusMessage.
 * Use `create(StatusMessageSchema)` to create a new message.
 */
export const StatusMessageSchema = /*@__PURE__*/
  messageDesc(file_statusmsg_v1_statusmsg, 0);

/**
 * Describes the enum statusmsg.v1.StatusCode.
 */
export const StatusCodeSchema = /*@__PURE__*/
  enumDesc(file_statusmsg_v1_statusmsg, 0);

/**
 * @generated from enum statusmsg.v1.StatusCode
 */
export const StatusCode = /*@__PURE__*/
  tsEnum(StatusCodeSchema);

