// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file property/v1/amenity.proto (package property.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { PaginationRequest, PaginationResponse } from "../../utils/v1/utils_pb";
import { file_utils_v1_utils } from "../../utils/v1/utils_pb";
import type { StatusMessage } from "../../statusmsg/v1/statusmsg_pb";
import { file_statusmsg_v1_statusmsg } from "../../statusmsg/v1/statusmsg_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file property/v1/amenity.proto.
 */
export const file_property_v1_amenity: GenFile = /*@__PURE__*/
  fileDesc("Chlwcm9wZXJ0eS92MS9hbWVuaXR5LnByb3RvEgtwcm9wZXJ0eS52MSJNCgxBbWVuaXR5TW9kZWwSDAoEZ3VpZBgCIAEoCRIMCgRuYW1lGAMgASgJEhMKC2Rlc2NyaXB0aW9uGAQgASgJEgwKBGljb24YBSABKAkiVgoVRmV0Y2hBbWVuaXRpZXNSZXF1ZXN0EgwKBG5hbWUYASABKAkSLwoKcGFnaW5hdGlvbhgDIAEoCzIbLnV0aWxzLnYxLlBhZ2luYXRpb25SZXF1ZXN0IqEBChZGZXRjaEFtZW5pdGllc1Jlc3BvbnNlEigKBWl0ZW1zGAEgAygLMhkucHJvcGVydHkudjEuQW1lbml0eU1vZGVsEjAKCnBhZ2luYXRpb24YAiABKAsyHC51dGlscy52MS5QYWdpbmF0aW9uUmVzcG9uc2USKwoGc3RhdHVzGAMgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2UihQEKHlNlYXJjaEFkdmFuY2VBbWVuaXRpZXNSZXNwb25zZRInCgRyb3dzGAEgAygLMhkucHJvcGVydHkudjEuQW1lbml0eU1vZGVsEg0KBXRvdGFsGAIgASgDEisKBnN0YXR1cxgDIAEoCzIbLnN0YXR1c21zZy52MS5TdGF0dXNNZXNzYWdlIkcKFENyZWF0ZUFtZW5pdHlSZXF1ZXN0EgwKBG5hbWUYASABKAkSEwoLZGVzY3JpcHRpb24YAiABKAkSDAoEaWNvbhgDIAEoCSJEChVDcmVhdGVBbWVuaXR5UmVzcG9uc2USKwoGc3RhdHVzGAEgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2UiVQoUVXBkYXRlQW1lbml0eVJlcXVlc3QSDAoEbmFtZRgBIAEoCRITCgtkZXNjcmlwdGlvbhgCIAEoCRIMCgRpY29uGAMgASgJEgwKBGd1aWQYBCABKAkiRAoVVXBkYXRlQW1lbml0eVJlc3BvbnNlEisKBnN0YXR1cxgBIAEoCzIbLnN0YXR1c21zZy52MS5TdGF0dXNNZXNzYWdlIiQKFERlbGV0ZUFtZW5pdHlSZXF1ZXN0EgwKBGd1aWQYASABKAkiRAoVRGVsZXRlQW1lbml0eVJlc3BvbnNlEisKBnN0YXR1cxgBIAEoCzIbLnN0YXR1c21zZy52MS5TdGF0dXNNZXNzYWdlQj1aO2dpdGh1Yi5jb20vbmdvY2h1eWs4MTIvcHJvdG8tYmRzL2dlbi9wcm9wZXJ0eS92MTtwcm9wZXJ0eXYxYgZwcm90bzM", [file_utils_v1_utils, file_statusmsg_v1_statusmsg]);

/**
 * @generated from message property.v1.AmenityModel
 */
export type AmenityModel = Message<"property.v1.AmenityModel"> & {
  /**
   * @generated from field: string guid = 2;
   */
  guid: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: string icon = 5;
   */
  icon: string;
};

/**
 * Describes the message property.v1.AmenityModel.
 * Use `create(AmenityModelSchema)` to create a new message.
 */
export const AmenityModelSchema: GenMessage<AmenityModel> = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 0);

/**
 * @generated from message property.v1.FetchAmenitiesRequest
 */
export type FetchAmenitiesRequest = Message<"property.v1.FetchAmenitiesRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: utils.v1.PaginationRequest pagination = 3;
   */
  pagination?: PaginationRequest;
};

/**
 * Describes the message property.v1.FetchAmenitiesRequest.
 * Use `create(FetchAmenitiesRequestSchema)` to create a new message.
 */
export const FetchAmenitiesRequestSchema: GenMessage<FetchAmenitiesRequest> = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 1);

/**
 * @generated from message property.v1.FetchAmenitiesResponse
 */
export type FetchAmenitiesResponse = Message<"property.v1.FetchAmenitiesResponse"> & {
  /**
   * @generated from field: repeated property.v1.AmenityModel items = 1;
   */
  items: AmenityModel[];

  /**
   * @generated from field: utils.v1.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse;

  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 3;
   */
  status?: StatusMessage;
};

/**
 * Describes the message property.v1.FetchAmenitiesResponse.
 * Use `create(FetchAmenitiesResponseSchema)` to create a new message.
 */
export const FetchAmenitiesResponseSchema: GenMessage<FetchAmenitiesResponse> = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 2);

/**
 * -----
 *
 * @generated from message property.v1.SearchAdvanceAmenitiesResponse
 */
export type SearchAdvanceAmenitiesResponse = Message<"property.v1.SearchAdvanceAmenitiesResponse"> & {
  /**
   * @generated from field: repeated property.v1.AmenityModel rows = 1;
   */
  rows: AmenityModel[];

  /**
   * @generated from field: int64 total = 2;
   */
  total: bigint;

  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 3;
   */
  status?: StatusMessage;
};

/**
 * Describes the message property.v1.SearchAdvanceAmenitiesResponse.
 * Use `create(SearchAdvanceAmenitiesResponseSchema)` to create a new message.
 */
export const SearchAdvanceAmenitiesResponseSchema: GenMessage<SearchAdvanceAmenitiesResponse> = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 3);

/**
 * -----
 *
 * @generated from message property.v1.CreateAmenityRequest
 */
export type CreateAmenityRequest = Message<"property.v1.CreateAmenityRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: string icon = 3;
   */
  icon: string;
};

/**
 * Describes the message property.v1.CreateAmenityRequest.
 * Use `create(CreateAmenityRequestSchema)` to create a new message.
 */
export const CreateAmenityRequestSchema: GenMessage<CreateAmenityRequest> = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 4);

/**
 * @generated from message property.v1.CreateAmenityResponse
 */
export type CreateAmenityResponse = Message<"property.v1.CreateAmenityResponse"> & {
  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 1;
   */
  status?: StatusMessage;
};

/**
 * Describes the message property.v1.CreateAmenityResponse.
 * Use `create(CreateAmenityResponseSchema)` to create a new message.
 */
export const CreateAmenityResponseSchema: GenMessage<CreateAmenityResponse> = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 5);

/**
 * @generated from message property.v1.UpdateAmenityRequest
 */
export type UpdateAmenityRequest = Message<"property.v1.UpdateAmenityRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: string icon = 3;
   */
  icon: string;

  /**
   * @generated from field: string guid = 4;
   */
  guid: string;
};

/**
 * Describes the message property.v1.UpdateAmenityRequest.
 * Use `create(UpdateAmenityRequestSchema)` to create a new message.
 */
export const UpdateAmenityRequestSchema: GenMessage<UpdateAmenityRequest> = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 6);

/**
 * @generated from message property.v1.UpdateAmenityResponse
 */
export type UpdateAmenityResponse = Message<"property.v1.UpdateAmenityResponse"> & {
  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 1;
   */
  status?: StatusMessage;
};

/**
 * Describes the message property.v1.UpdateAmenityResponse.
 * Use `create(UpdateAmenityResponseSchema)` to create a new message.
 */
export const UpdateAmenityResponseSchema: GenMessage<UpdateAmenityResponse> = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 7);

/**
 * @generated from message property.v1.DeleteAmenityRequest
 */
export type DeleteAmenityRequest = Message<"property.v1.DeleteAmenityRequest"> & {
  /**
   * @generated from field: string guid = 1;
   */
  guid: string;
};

/**
 * Describes the message property.v1.DeleteAmenityRequest.
 * Use `create(DeleteAmenityRequestSchema)` to create a new message.
 */
export const DeleteAmenityRequestSchema: GenMessage<DeleteAmenityRequest> = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 8);

/**
 * @generated from message property.v1.DeleteAmenityResponse
 */
export type DeleteAmenityResponse = Message<"property.v1.DeleteAmenityResponse"> & {
  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 1;
   */
  status?: StatusMessage;
};

/**
 * Describes the message property.v1.DeleteAmenityResponse.
 * Use `create(DeleteAmenityResponseSchema)` to create a new message.
 */
export const DeleteAmenityResponseSchema: GenMessage<DeleteAmenityResponse> = /*@__PURE__*/
  messageDesc(file_property_v1_amenity, 9);

