// @generated by protoc-gen-connect-es v1.1.0 with parameter "target=ts,import_extension=.js"
// @generated from file auth/v1/auth_service.proto (package auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateSiteRequest, CreateSiteResponse, DeleteSiteRequest, DeleteSiteResponse, FetchSitesRequest, FetchSitesResponse, UpdateSiteRequest, UpdateSiteResponse } from "./site_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { LoginRequest, LoginResponse, LogoutRequest, LogoutResponse, RefreshTokenRequest, RefreshTokenResponse, SignUpRequest, SignUpResponse, VerifySignUpRequest, VerifySignUpResponse } from "./auth_pb.js";
import { GetProfileRequest, GetProfileResponse, UpdateProfileRequest, UpdateProfileResponse } from "./user_pb.js";

/**
 * @generated from service auth.v1.AuthService
 */
export const AuthService = {
  typeName: "auth.v1.AuthService",
  methods: {
    /**
     * @generated from rpc auth.v1.AuthService.FetchSites
     */
    fetchSites: {
      name: "FetchSites",
      I: FetchSitesRequest,
      O: FetchSitesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.CreateSite
     */
    createSite: {
      name: "CreateSite",
      I: CreateSiteRequest,
      O: CreateSiteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.UpdateSite
     */
    updateSite: {
      name: "UpdateSite",
      I: UpdateSiteRequest,
      O: UpdateSiteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.DeleteSite
     */
    deleteSite: {
      name: "DeleteSite",
      I: DeleteSiteRequest,
      O: DeleteSiteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.SignUp
     */
    signUp: {
      name: "SignUp",
      I: SignUpRequest,
      O: SignUpResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.VerifySignUp
     */
    verifySignUp: {
      name: "VerifySignUp",
      I: VerifySignUpRequest,
      O: VerifySignUpResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.RefreshToken
     */
    refreshToken: {
      name: "RefreshToken",
      I: RefreshTokenRequest,
      O: RefreshTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.Logout
     */
    logout: {
      name: "Logout",
      I: LogoutRequest,
      O: LogoutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.GetProfile
     */
    getProfile: {
      name: "GetProfile",
      I: GetProfileRequest,
      O: GetProfileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.UpdateProfile
     */
    updateProfile: {
      name: "UpdateProfile",
      I: UpdateProfileRequest,
      O: UpdateProfileResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

