// @generated by protoc-gen-es v2.2.0 with parameter "target=js"
// @generated from file auth/v1/site.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_utils_v1_utils } from "../../utils/v1/utils_pb";
import { file_statusmsg_v1_statusmsg } from "../../statusmsg/v1/statusmsg_pb";

/**
 * Describes the file auth/v1/site.proto.
 */
export const file_auth_v1_site = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL3NpdGUucHJvdG8SB2F1dGgudjEiRAoJU2l0ZU1vZGVsEgoKAmlkGAEgASgDEgwKBGd1aWQYAiABKAkSDAoEbmFtZRgDIAEoCRIPCgdzaXRlX2lkGAQgASgJImMKEUZldGNoU2l0ZXNSZXF1ZXN0EgwKBG5hbWUYASABKAkSDwoHc2l0ZV9pZBgCIAEoCRIvCgpwYWdpbmF0aW9uGAMgASgLMhsudXRpbHMudjEuUGFnaW5hdGlvblJlcXVlc3QilgEKEkZldGNoU2l0ZXNSZXNwb25zZRIhCgVpdGVtcxgBIAMoCzISLmF1dGgudjEuU2l0ZU1vZGVsEjAKCnBhZ2luYXRpb24YAiABKAsyHC51dGlscy52MS5QYWdpbmF0aW9uUmVzcG9uc2USKwoGc3RhdHVzGAMgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2UiMgoRQ3JlYXRlU2l0ZVJlcXVlc3QSDAoEbmFtZRgBIAEoCRIPCgdzaXRlX2lkGAIgASgJIkEKEkNyZWF0ZVNpdGVSZXNwb25zZRIrCgZzdGF0dXMYASABKAsyGy5zdGF0dXNtc2cudjEuU3RhdHVzTWVzc2FnZSJAChFVcGRhdGVTaXRlUmVxdWVzdBIMCgRuYW1lGAEgASgJEg8KB3NpdGVfaWQYAiABKAkSDAoEZ3VpZBgDIAEoCSJBChJVcGRhdGVTaXRlUmVzcG9uc2USKwoGc3RhdHVzGAEgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2UiIQoRRGVsZXRlU2l0ZVJlcXVlc3QSDAoEZ3VpZBgBIAEoCSJBChJEZWxldGVTaXRlUmVzcG9uc2USKwoGc3RhdHVzGAEgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2VCNVozZ2l0aHViLmNvbS9uZ29jaHV5azgxMi9wcm90by1iZHMvZ2VuL2F1dGgvdjE7YXV0aHYxYgZwcm90bzM", [file_utils_v1_utils, file_statusmsg_v1_statusmsg]);

/**
 * Describes the message auth.v1.SiteModel.
 * Use `create(SiteModelSchema)` to create a new message.
 */
export const SiteModelSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 0);

/**
 * Describes the message auth.v1.FetchSitesRequest.
 * Use `create(FetchSitesRequestSchema)` to create a new message.
 */
export const FetchSitesRequestSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 1);

/**
 * Describes the message auth.v1.FetchSitesResponse.
 * Use `create(FetchSitesResponseSchema)` to create a new message.
 */
export const FetchSitesResponseSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 2);

/**
 * Describes the message auth.v1.CreateSiteRequest.
 * Use `create(CreateSiteRequestSchema)` to create a new message.
 */
export const CreateSiteRequestSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 3);

/**
 * Describes the message auth.v1.CreateSiteResponse.
 * Use `create(CreateSiteResponseSchema)` to create a new message.
 */
export const CreateSiteResponseSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 4);

/**
 * Describes the message auth.v1.UpdateSiteRequest.
 * Use `create(UpdateSiteRequestSchema)` to create a new message.
 */
export const UpdateSiteRequestSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 5);

/**
 * Describes the message auth.v1.UpdateSiteResponse.
 * Use `create(UpdateSiteResponseSchema)` to create a new message.
 */
export const UpdateSiteResponseSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 6);

/**
 * Describes the message auth.v1.DeleteSiteRequest.
 * Use `create(DeleteSiteRequestSchema)` to create a new message.
 */
export const DeleteSiteRequestSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 7);

/**
 * Describes the message auth.v1.DeleteSiteResponse.
 * Use `create(DeleteSiteResponseSchema)` to create a new message.
 */
export const DeleteSiteResponseSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 8);

