// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file auth/v1/site.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { PaginationRequest, PaginationResponse } from "../../utils/v1/utils_pb";
import { file_utils_v1_utils } from "../../utils/v1/utils_pb";
import type { StatusMessage } from "../../statusmsg/v1/statusmsg_pb";
import { file_statusmsg_v1_statusmsg } from "../../statusmsg/v1/statusmsg_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v1/site.proto.
 */
export const file_auth_v1_site: GenFile = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL3NpdGUucHJvdG8SB2F1dGgudjEiRAoJU2l0ZU1vZGVsEgoKAmlkGAEgASgDEgwKBGd1aWQYAiABKAkSDAoEbmFtZRgDIAEoCRIPCgdzaXRlX2lkGAQgASgJImMKEUZldGNoU2l0ZXNSZXF1ZXN0EgwKBG5hbWUYASABKAkSDwoHc2l0ZV9pZBgCIAEoCRIvCgpwYWdpbmF0aW9uGAMgASgLMhsudXRpbHMudjEuUGFnaW5hdGlvblJlcXVlc3QilgEKEkZldGNoU2l0ZXNSZXNwb25zZRIhCgVpdGVtcxgBIAMoCzISLmF1dGgudjEuU2l0ZU1vZGVsEjAKCnBhZ2luYXRpb24YAiABKAsyHC51dGlscy52MS5QYWdpbmF0aW9uUmVzcG9uc2USKwoGc3RhdHVzGAMgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2UiMgoRQ3JlYXRlU2l0ZVJlcXVlc3QSDAoEbmFtZRgBIAEoCRIPCgdzaXRlX2lkGAIgASgJIkEKEkNyZWF0ZVNpdGVSZXNwb25zZRIrCgZzdGF0dXMYASABKAsyGy5zdGF0dXNtc2cudjEuU3RhdHVzTWVzc2FnZSJAChFVcGRhdGVTaXRlUmVxdWVzdBIMCgRuYW1lGAEgASgJEg8KB3NpdGVfaWQYAiABKAkSDAoEZ3VpZBgDIAEoCSJBChJVcGRhdGVTaXRlUmVzcG9uc2USKwoGc3RhdHVzGAEgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2UiIQoRRGVsZXRlU2l0ZVJlcXVlc3QSDAoEZ3VpZBgBIAEoCSJBChJEZWxldGVTaXRlUmVzcG9uc2USKwoGc3RhdHVzGAEgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2VCNVozZ2l0aHViLmNvbS9uZ29jaHV5azgxMi9wcm90by1iZHMvZ2VuL2F1dGgvdjE7YXV0aHYxYgZwcm90bzM", [file_utils_v1_utils, file_statusmsg_v1_statusmsg]);

/**
 * @generated from message auth.v1.SiteModel
 */
export type SiteModel = Message<"auth.v1.SiteModel"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string guid = 2;
   */
  guid: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string site_id = 4;
   */
  siteId: string;
};

/**
 * Describes the message auth.v1.SiteModel.
 * Use `create(SiteModelSchema)` to create a new message.
 */
export const SiteModelSchema: GenMessage<SiteModel> = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 0);

/**
 * @generated from message auth.v1.FetchSitesRequest
 */
export type FetchSitesRequest = Message<"auth.v1.FetchSitesRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string site_id = 2;
   */
  siteId: string;

  /**
   * @generated from field: utils.v1.PaginationRequest pagination = 3;
   */
  pagination?: PaginationRequest;
};

/**
 * Describes the message auth.v1.FetchSitesRequest.
 * Use `create(FetchSitesRequestSchema)` to create a new message.
 */
export const FetchSitesRequestSchema: GenMessage<FetchSitesRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 1);

/**
 * @generated from message auth.v1.FetchSitesResponse
 */
export type FetchSitesResponse = Message<"auth.v1.FetchSitesResponse"> & {
  /**
   * @generated from field: repeated auth.v1.SiteModel items = 1;
   */
  items: SiteModel[];

  /**
   * @generated from field: utils.v1.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse;

  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 3;
   */
  status?: StatusMessage;
};

/**
 * Describes the message auth.v1.FetchSitesResponse.
 * Use `create(FetchSitesResponseSchema)` to create a new message.
 */
export const FetchSitesResponseSchema: GenMessage<FetchSitesResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 2);

/**
 * -----
 *
 * @generated from message auth.v1.CreateSiteRequest
 */
export type CreateSiteRequest = Message<"auth.v1.CreateSiteRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string site_id = 2;
   */
  siteId: string;
};

/**
 * Describes the message auth.v1.CreateSiteRequest.
 * Use `create(CreateSiteRequestSchema)` to create a new message.
 */
export const CreateSiteRequestSchema: GenMessage<CreateSiteRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 3);

/**
 * @generated from message auth.v1.CreateSiteResponse
 */
export type CreateSiteResponse = Message<"auth.v1.CreateSiteResponse"> & {
  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 1;
   */
  status?: StatusMessage;
};

/**
 * Describes the message auth.v1.CreateSiteResponse.
 * Use `create(CreateSiteResponseSchema)` to create a new message.
 */
export const CreateSiteResponseSchema: GenMessage<CreateSiteResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 4);

/**
 * @generated from message auth.v1.UpdateSiteRequest
 */
export type UpdateSiteRequest = Message<"auth.v1.UpdateSiteRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string site_id = 2;
   */
  siteId: string;

  /**
   * @generated from field: string guid = 3;
   */
  guid: string;
};

/**
 * Describes the message auth.v1.UpdateSiteRequest.
 * Use `create(UpdateSiteRequestSchema)` to create a new message.
 */
export const UpdateSiteRequestSchema: GenMessage<UpdateSiteRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 5);

/**
 * @generated from message auth.v1.UpdateSiteResponse
 */
export type UpdateSiteResponse = Message<"auth.v1.UpdateSiteResponse"> & {
  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 1;
   */
  status?: StatusMessage;
};

/**
 * Describes the message auth.v1.UpdateSiteResponse.
 * Use `create(UpdateSiteResponseSchema)` to create a new message.
 */
export const UpdateSiteResponseSchema: GenMessage<UpdateSiteResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 6);

/**
 * @generated from message auth.v1.DeleteSiteRequest
 */
export type DeleteSiteRequest = Message<"auth.v1.DeleteSiteRequest"> & {
  /**
   * @generated from field: string guid = 1;
   */
  guid: string;
};

/**
 * Describes the message auth.v1.DeleteSiteRequest.
 * Use `create(DeleteSiteRequestSchema)` to create a new message.
 */
export const DeleteSiteRequestSchema: GenMessage<DeleteSiteRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 7);

/**
 * @generated from message auth.v1.DeleteSiteResponse
 */
export type DeleteSiteResponse = Message<"auth.v1.DeleteSiteResponse"> & {
  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 1;
   */
  status?: StatusMessage;
};

/**
 * Describes the message auth.v1.DeleteSiteResponse.
 * Use `create(DeleteSiteResponseSchema)` to create a new message.
 */
export const DeleteSiteResponseSchema: GenMessage<DeleteSiteResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_site, 8);

