// @generated by protoc-gen-es v2.2.0 with parameter "target=js"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_statusmsg_v1_statusmsg } from "../../statusmsg/v1/statusmsg_pb";

/**
 * Describes the file auth/v1/auth.proto.
 */
export const file_auth_v1_auth = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL2F1dGgucHJvdG8SB2F1dGgudjEiLwoMTG9naW5SZXF1ZXN0Eg0KBWVtYWlsGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJImkKDUxvZ2luUmVzcG9uc2USFAoMYWNjZXNzX3Rva2VuGAEgASgJEhUKDXJlZnJlc2hfdG9rZW4YAiABKAkSKwoGc3RhdHVzGAMgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2UiQwoNU2lnblVwUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCRIRCglmdWxsX25hbWUYAyABKAkiPQoOU2lnblVwUmVzcG9uc2USKwoGc3RhdHVzGAEgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2UiMQoTVmVyaWZ5U2lnblVwUmVxdWVzdBINCgVlbWFpbBgBIAEoCRILCgNvdHAYAiABKAkiQwoUVmVyaWZ5U2lnblVwUmVzcG9uc2USKwoGc3RhdHVzGAEgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2UiLAoTUmVmcmVzaFRva2VuUmVxdWVzdBIVCg1yZWZyZXNoX3Rva2VuGAEgASgJInAKFFJlZnJlc2hUb2tlblJlc3BvbnNlEhQKDGFjY2Vzc190b2tlbhgBIAEoCRIVCg1yZWZyZXNoX3Rva2VuGAIgASgJEisKBnN0YXR1cxgDIAEoCzIbLnN0YXR1c21zZy52MS5TdGF0dXNNZXNzYWdlIg8KDUxvZ291dFJlcXVlc3QiPQoOTG9nb3V0UmVzcG9uc2USKwoGc3RhdHVzGAEgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2VCNVozZ2l0aHViLmNvbS9uZ29jaHV5azgxMi9wcm90by1iZHMvZ2VuL2F1dGgvdjE7YXV0aHYxYgZwcm90bzM", [file_statusmsg_v1_statusmsg]);

/**
 * Describes the message auth.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 0);

/**
 * Describes the message auth.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 1);

/**
 * Describes the message auth.v1.SignUpRequest.
 * Use `create(SignUpRequestSchema)` to create a new message.
 */
export const SignUpRequestSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 2);

/**
 * Describes the message auth.v1.SignUpResponse.
 * Use `create(SignUpResponseSchema)` to create a new message.
 */
export const SignUpResponseSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 3);

/**
 * Describes the message auth.v1.VerifySignUpRequest.
 * Use `create(VerifySignUpRequestSchema)` to create a new message.
 */
export const VerifySignUpRequestSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 4);

/**
 * Describes the message auth.v1.VerifySignUpResponse.
 * Use `create(VerifySignUpResponseSchema)` to create a new message.
 */
export const VerifySignUpResponseSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 5);

/**
 * Describes the message auth.v1.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 6);

/**
 * Describes the message auth.v1.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export const RefreshTokenResponseSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 7);

/**
 * Describes the message auth.v1.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 8);

/**
 * Describes the message auth.v1.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 9);

