// @generated by protoc-gen-es v2.2.0 with parameter "target=js"
// @generated from file auth/v1/user.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_statusmsg_v1_statusmsg } from "../../statusmsg/v1/statusmsg_pb";

/**
 * Describes the file auth/v1/user.proto.
 */
export const file_auth_v1_user = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL3VzZXIucHJvdG8SB2F1dGgudjEidgoKVXNlckRldGFpbBIRCgl1c2VyX2d1aWQYASABKAkSEgoKZmlyc3RfbmFtZRgCIAEoCRIRCglsYXN0X25hbWUYAyABKAkSDQoFcGhvbmUYBCABKAkSDwoHYWRkcmVzcxgFIAEoCRIOCgZhdmF0YXIYBiABKAkibQoUVXBkYXRlUHJvZmlsZVJlcXVlc3QSEgoKZmlyc3RfbmFtZRgBIAEoCRIRCglsYXN0X25hbWUYAiABKAkSDQoFcGhvbmUYAyABKAkSDwoHYWRkcmVzcxgEIAEoCRIOCgZhdmF0YXIYBSABKAkiRAoVVXBkYXRlUHJvZmlsZVJlc3BvbnNlEisKBnN0YXR1cxgBIAEoCzIbLnN0YXR1c21zZy52MS5TdGF0dXNNZXNzYWdlIhMKEUdldFByb2ZpbGVSZXF1ZXN0ImcKEkdldFByb2ZpbGVSZXNwb25zZRIkCgdwcm9maWxlGAEgASgLMhMuYXV0aC52MS5Vc2VyRGV0YWlsEisKBnN0YXR1cxgCIAEoCzIbLnN0YXR1c21zZy52MS5TdGF0dXNNZXNzYWdlQjVaM2dpdGh1Yi5jb20vbmdvY2h1eWs4MTIvcHJvdG8tYmRzL2dlbi9hdXRoL3YxO2F1dGh2MWIGcHJvdG8z", [file_statusmsg_v1_statusmsg]);

/**
 * Describes the message auth.v1.UserDetail.
 * Use `create(UserDetailSchema)` to create a new message.
 */
export const UserDetailSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_user, 0);

/**
 * Describes the message auth.v1.UpdateProfileRequest.
 * Use `create(UpdateProfileRequestSchema)` to create a new message.
 */
export const UpdateProfileRequestSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_user, 1);

/**
 * Describes the message auth.v1.UpdateProfileResponse.
 * Use `create(UpdateProfileResponseSchema)` to create a new message.
 */
export const UpdateProfileResponseSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_user, 2);

/**
 * Describes the message auth.v1.GetProfileRequest.
 * Use `create(GetProfileRequestSchema)` to create a new message.
 */
export const GetProfileRequestSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_user, 3);

/**
 * Describes the message auth.v1.GetProfileResponse.
 * Use `create(GetProfileResponseSchema)` to create a new message.
 */
export const GetProfileResponseSchema = /*@__PURE__*/
  messageDesc(file_auth_v1_user, 4);

