// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file auth/v1/user.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { StatusMessage } from "../../statusmsg/v1/statusmsg_pb";
import { file_statusmsg_v1_statusmsg } from "../../statusmsg/v1/statusmsg_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v1/user.proto.
 */
export const file_auth_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL3VzZXIucHJvdG8SB2F1dGgudjEidgoKVXNlckRldGFpbBIRCgl1c2VyX2d1aWQYASABKAkSEgoKZmlyc3RfbmFtZRgCIAEoCRIRCglsYXN0X25hbWUYAyABKAkSDQoFcGhvbmUYBCABKAkSDwoHYWRkcmVzcxgFIAEoCRIOCgZhdmF0YXIYBiABKAkibQoUVXBkYXRlUHJvZmlsZVJlcXVlc3QSEgoKZmlyc3RfbmFtZRgBIAEoCRIRCglsYXN0X25hbWUYAiABKAkSDQoFcGhvbmUYAyABKAkSDwoHYWRkcmVzcxgEIAEoCRIOCgZhdmF0YXIYBSABKAkiRAoVVXBkYXRlUHJvZmlsZVJlc3BvbnNlEisKBnN0YXR1cxgBIAEoCzIbLnN0YXR1c21zZy52MS5TdGF0dXNNZXNzYWdlIhMKEUdldFByb2ZpbGVSZXF1ZXN0ImcKEkdldFByb2ZpbGVSZXNwb25zZRIkCgdwcm9maWxlGAEgASgLMhMuYXV0aC52MS5Vc2VyRGV0YWlsEisKBnN0YXR1cxgCIAEoCzIbLnN0YXR1c21zZy52MS5TdGF0dXNNZXNzYWdlQjVaM2dpdGh1Yi5jb20vbmdvY2h1eWs4MTIvcHJvdG8tYmRzL2dlbi9hdXRoL3YxO2F1dGh2MWIGcHJvdG8z", [file_statusmsg_v1_statusmsg]);

/**
 * @generated from message auth.v1.UserDetail
 */
export type UserDetail = Message<"auth.v1.UserDetail"> & {
  /**
   * @generated from field: string user_guid = 1;
   */
  userGuid: string;

  /**
   * @generated from field: string first_name = 2;
   */
  firstName: string;

  /**
   * @generated from field: string last_name = 3;
   */
  lastName: string;

  /**
   * @generated from field: string phone = 4;
   */
  phone: string;

  /**
   * @generated from field: string address = 5;
   */
  address: string;

  /**
   * @generated from field: string avatar = 6;
   */
  avatar: string;
};

/**
 * Describes the message auth.v1.UserDetail.
 * Use `create(UserDetailSchema)` to create a new message.
 */
export const UserDetailSchema: GenMessage<UserDetail> = /*@__PURE__*/
  messageDesc(file_auth_v1_user, 0);

/**
 * @generated from message auth.v1.UpdateProfileRequest
 */
export type UpdateProfileRequest = Message<"auth.v1.UpdateProfileRequest"> & {
  /**
   * @generated from field: string first_name = 1;
   */
  firstName: string;

  /**
   * @generated from field: string last_name = 2;
   */
  lastName: string;

  /**
   * @generated from field: string phone = 3;
   */
  phone: string;

  /**
   * @generated from field: string address = 4;
   */
  address: string;

  /**
   * @generated from field: string avatar = 5;
   */
  avatar: string;
};

/**
 * Describes the message auth.v1.UpdateProfileRequest.
 * Use `create(UpdateProfileRequestSchema)` to create a new message.
 */
export const UpdateProfileRequestSchema: GenMessage<UpdateProfileRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_user, 1);

/**
 * @generated from message auth.v1.UpdateProfileResponse
 */
export type UpdateProfileResponse = Message<"auth.v1.UpdateProfileResponse"> & {
  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 1;
   */
  status?: StatusMessage;
};

/**
 * Describes the message auth.v1.UpdateProfileResponse.
 * Use `create(UpdateProfileResponseSchema)` to create a new message.
 */
export const UpdateProfileResponseSchema: GenMessage<UpdateProfileResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_user, 2);

/**
 * @generated from message auth.v1.GetProfileRequest
 */
export type GetProfileRequest = Message<"auth.v1.GetProfileRequest"> & {
};

/**
 * Describes the message auth.v1.GetProfileRequest.
 * Use `create(GetProfileRequestSchema)` to create a new message.
 */
export const GetProfileRequestSchema: GenMessage<GetProfileRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_user, 3);

/**
 * @generated from message auth.v1.GetProfileResponse
 */
export type GetProfileResponse = Message<"auth.v1.GetProfileResponse"> & {
  /**
   * @generated from field: auth.v1.UserDetail profile = 1;
   */
  profile?: UserDetail;

  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 2;
   */
  status?: StatusMessage;
};

/**
 * Describes the message auth.v1.GetProfileResponse.
 * Use `create(GetProfileResponseSchema)` to create a new message.
 */
export const GetProfileResponseSchema: GenMessage<GetProfileResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_user, 4);

