// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package site

import (
	"database/sql"
)

type Site struct {
	ID        int32
	Guid      string
	Siteid    string
	Name      string
	Createdat int64
	Updatedat sql.NullInt64
	Deletedat sql.NullInt64
}
