version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8111:8080"
    restart: always
    networks:
      - dev-network
networks:
  dev-network:
    external: true