@Library('devops@develop') _

pipeline {
    agent any
    environment {
        SERVICE_NAME = "auth-service"
    }
    stages {
        stage('Build & Deploy') {
            steps {
                script {
                    buildHelper(env.SERVICE_NAME)
                }
            }
        }
    }
}
