pipeline {
    agent any

    environment {
        SERVICE = 'auth-service'
    }

    stages {
        stage('Build') {
            steps {
                sh 'docker compose -f ${SERVICE}/docker-compose.yml build'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker compose -f ${SERVICE}/docker-compose.yml up -d'
            }
        }
    }

    post {
        failure {
            echo "Build failed"
        }
        success {
            echo "App is running!"
        }
    }
}
