@Library('devops@develop') _

pipeline {
    agent none
    environment {
        SERVICE_NAME = "auth-service"
    }
    stages {
        stage('Build') {
            agent any
            steps {
                script {
                    buildHelper(env.SERVICE_NAME)
                }
            }
        }
    }
}
