// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file utils/v1/utils.proto (package utils.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { StatusMessage } from "../../statusmsg/v1/statusmsg_pb";
import { file_statusmsg_v1_statusmsg } from "../../statusmsg/v1/statusmsg_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file utils/v1/utils.proto.
 */
export const file_utils_v1_utils: GenFile = /*@__PURE__*/
  fileDesc("ChR1dGlscy92MS91dGlscy5wcm90bxIIdXRpbHMudjEiOwoRUGFnaW5hdGlvblJlcXVlc3QSEQoJcGFnZV9zaXplGAEgASgDEhMKC3BhZ2VfbnVtYmVyGAIgASgDImEKElBhZ2luYXRpb25SZXNwb25zZRIUCgxjdXJyZW50X3BhZ2UYASABKAMSEQoJcGFnZV9zaXplGAIgASgDEg0KBXRvdGFsGAMgASgDEhMKC3RvdGFsX3BhZ2VzGAQgASgDIjkKCkZpbHRlckl0ZW0SDQoFZmllbGQYASABKAkSDAoEdHlwZRgCIAEoCRIOCgZmaWx0ZXIYAyABKAkiLQoNU29ydE1vZGVsSXRlbRIOCgZjb2xfaWQYASABKAkSDAoEc29ydBgCIAEoCSKIAQoUU2VhcmNoQWR2YW5jZVJlcXVlc3QSJQoHZmlsdGVycxgBIAMoCzIULnV0aWxzLnYxLkZpbHRlckl0ZW0SJQoEc29ydBgCIAMoCzIXLnV0aWxzLnYxLlNvcnRNb2RlbEl0ZW0SEQoJc3RhcnRfcm93GAMgASgFEg8KB2VuZF9yb3cYBCABKAUiOwoMQmFzZVJlc3BvbnNlEisKBnN0YXR1cxgBIAEoCzIbLnN0YXR1c21zZy52MS5TdGF0dXNNZXNzYWdlQjdaNWdpdGh1Yi5jb20vbmdvY2h1eWs4MTIvcHJvdG8tYmRzL2dlbi91dGlscy92MTt1dGlsc3YxYgZwcm90bzM", [file_statusmsg_v1_statusmsg]);

/**
 * @generated from message utils.v1.PaginationRequest
 */
export type PaginationRequest = Message<"utils.v1.PaginationRequest"> & {
  /**
   * @generated from field: int64 page_size = 1;
   */
  pageSize: bigint;

  /**
   * @generated from field: int64 page_number = 2;
   */
  pageNumber: bigint;
};

/**
 * Describes the message utils.v1.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export const PaginationRequestSchema: GenMessage<PaginationRequest> = /*@__PURE__*/
  messageDesc(file_utils_v1_utils, 0);

/**
 * @generated from message utils.v1.PaginationResponse
 */
export type PaginationResponse = Message<"utils.v1.PaginationResponse"> & {
  /**
   * @generated from field: int64 current_page = 1;
   */
  currentPage: bigint;

  /**
   * @generated from field: int64 page_size = 2;
   */
  pageSize: bigint;

  /**
   * @generated from field: int64 total = 3;
   */
  total: bigint;

  /**
   * @generated from field: int64 total_pages = 4;
   */
  totalPages: bigint;
};

/**
 * Describes the message utils.v1.PaginationResponse.
 * Use `create(PaginationResponseSchema)` to create a new message.
 */
export const PaginationResponseSchema: GenMessage<PaginationResponse> = /*@__PURE__*/
  messageDesc(file_utils_v1_utils, 1);

/**
 * @generated from message utils.v1.FilterItem
 */
export type FilterItem = Message<"utils.v1.FilterItem"> & {
  /**
   * @generated from field: string field = 1;
   */
  field: string;

  /**
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * @generated from field: string filter = 3;
   */
  filter: string;
};

/**
 * Describes the message utils.v1.FilterItem.
 * Use `create(FilterItemSchema)` to create a new message.
 */
export const FilterItemSchema: GenMessage<FilterItem> = /*@__PURE__*/
  messageDesc(file_utils_v1_utils, 2);

/**
 * @generated from message utils.v1.SortModelItem
 */
export type SortModelItem = Message<"utils.v1.SortModelItem"> & {
  /**
   * @generated from field: string col_id = 1;
   */
  colId: string;

  /**
   * @generated from field: string sort = 2;
   */
  sort: string;
};

/**
 * Describes the message utils.v1.SortModelItem.
 * Use `create(SortModelItemSchema)` to create a new message.
 */
export const SortModelItemSchema: GenMessage<SortModelItem> = /*@__PURE__*/
  messageDesc(file_utils_v1_utils, 3);

/**
 * @generated from message utils.v1.SearchAdvanceRequest
 */
export type SearchAdvanceRequest = Message<"utils.v1.SearchAdvanceRequest"> & {
  /**
   * @generated from field: repeated utils.v1.FilterItem filters = 1;
   */
  filters: FilterItem[];

  /**
   * @generated from field: repeated utils.v1.SortModelItem sort = 2;
   */
  sort: SortModelItem[];

  /**
   * @generated from field: int32 start_row = 3;
   */
  startRow: number;

  /**
   * @generated from field: int32 end_row = 4;
   */
  endRow: number;
};

/**
 * Describes the message utils.v1.SearchAdvanceRequest.
 * Use `create(SearchAdvanceRequestSchema)` to create a new message.
 */
export const SearchAdvanceRequestSchema: GenMessage<SearchAdvanceRequest> = /*@__PURE__*/
  messageDesc(file_utils_v1_utils, 4);

/**
 * @generated from message utils.v1.BaseResponse
 */
export type BaseResponse = Message<"utils.v1.BaseResponse"> & {
  /**
   * @generated from field: statusmsg.v1.StatusMessage status = 1;
   */
  status?: StatusMessage;
};

/**
 * Describes the message utils.v1.BaseResponse.
 * Use `create(BaseResponseSchema)` to create a new message.
 */
export const BaseResponseSchema: GenMessage<BaseResponse> = /*@__PURE__*/
  messageDesc(file_utils_v1_utils, 5);

