// @generated by protoc-gen-es v2.2.0 with parameter "target=js"
// @generated from file internal/v1/internal.proto (package internal.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_statusmsg_v1_statusmsg } from "../../statusmsg/v1/statusmsg_pb";

/**
 * Describes the file internal/v1/internal.proto.
 */
export const file_internal_v1_internal = /*@__PURE__*/
  fileDesc("ChppbnRlcm5hbC92MS9pbnRlcm5hbC5wcm90bxILaW50ZXJuYWwudjEiRgoXSW50ZXJuYWxTZXJ2aWNlUmVzcG9uc2USKwoGc3RhdHVzGAEgASgLMhsuc3RhdHVzbXNnLnYxLlN0YXR1c01lc3NhZ2VCPVo7Z2l0aHViLmNvbS9uZ29jaHV5azgxMi9wcm90by1iZHMvZ2VuL2ludGVybmFsL3YxO2ludGVybmFsdjFiBnByb3RvMw", [file_statusmsg_v1_statusmsg]);

/**
 * Describes the message internal.v1.InternalServiceResponse.
 * Use `create(InternalServiceResponseSchema)` to create a new message.
 */
export const InternalServiceResponseSchema = /*@__PURE__*/
  messageDesc(file_internal_v1_internal, 0);

