// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package user

import (
	"database/sql"
)

type User struct {
	ID           int32
	Guid         string
	Siteid       string
	Email        string
	HashPassword string
	Salt         string
	Createdat    int64
	Updatedat    sql.NullInt64
	Deletedat    sql.NullInt64
}
