version: '3.8'

services:
  sender-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8112:8080"
    restart: always
    networks:
      - dev-network
networks:
  dev-network:
    external: true