// @generated by protoc-gen-connect-es v1.1.0 with parameter "target=ts,import_extension=.js"
// @generated from file property/v1/property_service.proto (package property.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateAmenityRequest, CreateAmenityResponse, DeleteAmenityRequest, DeleteAmenityResponse, FetchAmenitiesRequest, FetchAmenitiesResponse, SearchAdvanceAmenitiesResponse, UpdateAmenityRequest, UpdateAmenityResponse } from "./amenity_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { SearchAdvanceRequest } from "../../utils/v1/utils_pb.js";

/**
 * @generated from service property.v1.PropertyService
 */
export const PropertyService = {
  typeName: "property.v1.PropertyService",
  methods: {
    /**
     * @generated from rpc property.v1.PropertyService.FetchAmenities
     */
    fetchAmenities: {
      name: "FetchAmenities",
      I: FetchAmenitiesRequest,
      O: FetchAmenitiesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc property.v1.PropertyService.SearchAdvanceAmenities
     */
    searchAdvanceAmenities: {
      name: "SearchAdvanceAmenities",
      I: SearchAdvanceRequest,
      O: SearchAdvanceAmenitiesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc property.v1.PropertyService.CreateAmenity
     */
    createAmenity: {
      name: "CreateAmenity",
      I: CreateAmenityRequest,
      O: CreateAmenityResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc property.v1.PropertyService.UpdateAmenity
     */
    updateAmenity: {
      name: "UpdateAmenity",
      I: UpdateAmenityRequest,
      O: UpdateAmenityResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc property.v1.PropertyService.DeleteAmenity
     */
    deleteAmenity: {
      name: "DeleteAmenity",
      I: DeleteAmenityRequest,
      O: DeleteAmenityResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

