// @generated by protoc-gen-es v2.2.0 with parameter "target=js"
// @generated from file utils/v1/utils.proto (package utils.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_statusmsg_v1_statusmsg } from "../../statusmsg/v1/statusmsg_pb";

/**
 * Describes the file utils/v1/utils.proto.
 */
export const file_utils_v1_utils = /*@__PURE__*/
  fileDesc("ChR1dGlscy92MS91dGlscy5wcm90bxIIdXRpbHMudjEiOwoRUGFnaW5hdGlvblJlcXVlc3QSEQoJcGFnZV9zaXplGAEgASgDEhMKC3BhZ2VfbnVtYmVyGAIgASgDImEKElBhZ2luYXRpb25SZXNwb25zZRIUCgxjdXJyZW50X3BhZ2UYASABKAMSEQoJcGFnZV9zaXplGAIgASgDEg0KBXRvdGFsGAMgASgDEhMKC3RvdGFsX3BhZ2VzGAQgASgDIjkKCkZpbHRlckl0ZW0SDQoFZmllbGQYASABKAkSDAoEdHlwZRgCIAEoCRIOCgZmaWx0ZXIYAyABKAkiLQoNU29ydE1vZGVsSXRlbRIOCgZjb2xfaWQYASABKAkSDAoEc29ydBgCIAEoCSKIAQoUU2VhcmNoQWR2YW5jZVJlcXVlc3QSJQoHZmlsdGVycxgBIAMoCzIULnV0aWxzLnYxLkZpbHRlckl0ZW0SJQoEc29ydBgCIAMoCzIXLnV0aWxzLnYxLlNvcnRNb2RlbEl0ZW0SEQoJc3RhcnRfcm93GAMgASgFEg8KB2VuZF9yb3cYBCABKAUiOwoMQmFzZVJlc3BvbnNlEisKBnN0YXR1cxgBIAEoCzIbLnN0YXR1c21zZy52MS5TdGF0dXNNZXNzYWdlQjdaNWdpdGh1Yi5jb20vbmdvY2h1eWs4MTIvcHJvdG8tYmRzL2dlbi91dGlscy92MTt1dGlsc3YxYgZwcm90bzM", [file_statusmsg_v1_statusmsg]);

/**
 * Describes the message utils.v1.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export const PaginationRequestSchema = /*@__PURE__*/
  messageDesc(file_utils_v1_utils, 0);

/**
 * Describes the message utils.v1.PaginationResponse.
 * Use `create(PaginationResponseSchema)` to create a new message.
 */
export const PaginationResponseSchema = /*@__PURE__*/
  messageDesc(file_utils_v1_utils, 1);

/**
 * Describes the message utils.v1.FilterItem.
 * Use `create(FilterItemSchema)` to create a new message.
 */
export const FilterItemSchema = /*@__PURE__*/
  messageDesc(file_utils_v1_utils, 2);

/**
 * Describes the message utils.v1.SortModelItem.
 * Use `create(SortModelItemSchema)` to create a new message.
 */
export const SortModelItemSchema = /*@__PURE__*/
  messageDesc(file_utils_v1_utils, 3);

/**
 * Describes the message utils.v1.SearchAdvanceRequest.
 * Use `create(SearchAdvanceRequestSchema)` to create a new message.
 */
export const SearchAdvanceRequestSchema = /*@__PURE__*/
  messageDesc(file_utils_v1_utils, 4);

/**
 * Describes the message utils.v1.BaseResponse.
 * Use `create(BaseResponseSchema)` to create a new message.
 */
export const BaseResponseSchema = /*@__PURE__*/
  messageDesc(file_utils_v1_utils, 5);

